lab5 create
dmbrson/weather pull request #1
Opened 2024-01-19 11:13 UTC by dmbrson

2024-01-19 11:28 UTC, hattorihanzooo commented
всё списал!

2024-01-20 01:04 UTC, Hostridet commented
> всё списал!

я тоже

2024-01-20 01:24 UTC, Hostridet requested changes

2024-01-20 01:24 UTC, Hostridet commented on lib/models.dart
> +  String get iconUrl {
Доменная модель не должна знать о url, вынести на экран

2024-01-20 01:24 UTC, Hostridet commented on lib/service.dart
> +  Future<WeatherResponse> getWeather(String city, BuildContext context) async {
Убрать отсюда контекст и больше никогда не передавать!
Сервис не должен знать о элементе виджета, передавай в параметрах сразу язык
тем более контекст может измениться во время выполнения асинхронного метода

2024-01-20 01:24 UTC, Hostridet commented on lib/service.dart
> +      'lang': AppLocalizations.of(context)!.language,
тоже исправить

2024-01-20 01:24 UTC, Hostridet commented on lib/service.dart
> +    final response = await http.get(uri);
запрос в `try {} catch{}`

2024-01-20 01:24 UTC, Hostridet commented on lib/service.dart
> +    final json = jsonDecode(response.body);
Зачем парсить json, если придет 400 или 500?
нужно парсить только при 200
UPD: ошибку исключением отловить

2024-01-20 01:24 UTC, Hostridet commented on lib/main.dart
> +  final String title;
Зачем передавать тайтл, если он всегда один и тот же?

2024-01-20 01:25 UTC, Hostridet commented on lib/main.dart
> +  void search() async {
`Future<void> search() async {`

2024-01-22 10:27 UTC, closed without merging